name: QGIS tests

on:
  push:
    branches:
      - master
      - test-focal
      - release-**
    paths:
    - 'src/**'
    - 'external/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - '.github/workflows/**'
    - '.docker/**'
  pull_request:
    branches:
      - master
      - release-**
    paths:
    - 'src/**'
    - 'external/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - '.github/workflows/**'
    - '.docker/**'

jobs:
  build:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_WORKSPACE: ${{ github.workspace }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set vars
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          DOCKER_TAG=$( [[ ${GITHUB_EVENT_NAME} =~ ^pull_request$ ]] && echo ${GITHUB_BASE_REF} || echo ${GITHUB_REF##*/} )
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Print vars
        run: |
          echo DOCKER_TAG: ${DOCKER_TAG}

      - name: Build deps
        run: |
          pushd .docker
          docker pull qgis/qgis3-build-deps:${DOCKER_TAG}
          docker build --cache-from qgis/qgis3-build-deps:${DOCKER_TAG} -t qgis/qgis3-build-deps:${DOCKER_TAG} -f qgis3-build-deps.dockerfile .
          popd

      - name: Push deps image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
          docker push "qgis/qgis3-build-deps:${DOCKER_TAG}"

      - name: Compile QGIS
        run: |
          docker run -t --name qgis_container \
                     -v $(pwd):/root/QGIS \
                     --env-file .docker/docker-variables.env \
                     qgis/qgis3-build-deps:${DOCKER_TAG} \
                     /root/QGIS/.docker/docker-qgis-build.sh
          docker commit qgis_container qgis_image

      - name: run unit tests
        run: |
          docker-compose -f .docker/docker-compose-testing.yml run qgis-deps /root/QGIS/.docker/docker-qgis-test.sh

      - name: QGIS runners
        run: |
          docker run -d --name qgis-testing-environment \
                     -v $(pwd):/root/QGIS \
                     -v $(pwd)/tests/src/python:/tests_directory \
                     -v $(pwd)/.docker/qgis_resources/test_runner:/usr/bin/test_runner \
                     -v $(pwd)/.docker/qgis_resources/supervisor:/etc/supervisor \
                     -e QGIS_BUILD_PATH=/root/QGIS/build/output/bin/qgis \
                     -e TEST_RUNNER_PATH=/usr/bin/test_runner/qgis_testrunner.py \
                     -e DISPLAY=:99 \
                     qgis_image \
                     /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
          # Wait for xvfb to finish starting
          printf "Waiting for the docker...🐳..."
          sleep 10
          echo " done 🥩"

          declare -A testrunners
          # Passing cases:
          testrunners["test_testrunner.run_passing"]=0
          testrunners["test_testrunner.run_skipped_and_passing"]=0
          # Failing cases:
          testrunners["test_testrunner"]=1
          testrunners["test_testrunner.run_all"]=1
          testrunners["test_testrunner.run_failing"]=1
          set +e # do not exit on error
          # Run tests in the docker
          for i in "${!testrunners[@]}"
          do
            echo "travis_fold:start:docker_test_runner_${i}"
            echo "test ${i}..."
            docker exec -it qgis-testing-environment sh -c "cd /tests_directory && /usr/bin/test_runner/qgis_testrunner.sh ${i}"
            [[ $? -eq "${testrunners[$i]}" ]] && echo "success" || exit 1
            echo "travis_fold:end:docker_test_runner_${i}"
          done
          set -e # switch back
          docker stop qgis-testing-environment

